version: '2'
services:
  cadvisor:
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
      - "/var/run/docker.sock/:/var/run/docker.sock:ro"

  node-exporter:
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: prom/node-exporter:latest
    stdin_open: true

  prometheus:
      tty: true
      build: ./
      command: -alertmanager.url=http://alertmanager:9093 -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
      ports:
        - 9090:9090
      links:
        - cadvisor:cadvisor
        - node-exporter:node-exporter
        - prometheus-rancher-exporter:prometheus-rancher-exporter
        - event-service:event-service
        - rails:rails

  influxdb:
    image: tutum/influxdb:0.10
    ports:
      - 2003:2003
      - 8083:8083
      - 8086:8086
    environment:
      - PRE_CREATE_DB=grafana;prometheus;rancher
      - GRAPHITE_DB=rancher
      - GRAPHITE_BINDING=:2003

  graf-db:
      tty: true
      image: infinityworks/graf-db:10
      command: cat
      volumes:
        - /var/lib/grafana/

  grafana:
      tty: true
      image: grafana/grafana:3.0.1
      ports:
        - 3000:3000
      volumes_from:
        - graf-db
      links:
        - prometheus:prometheus
        - prometheus-rancher-exporter:prometheus-rancher-exporter

  prometheus-rancher-exporter:
      tty: true
      labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent.role: environment
      image: infinityworks/prometheus-rancher-exporter:04

  mongo:
    image: mongo

  event-service:
    image: iambowen/event-service
    environment:
      SPRING_PROFILES_ACTIVE: pact-test
      SERVER_PORT: 8080
    ports:
      - "8888:8080"
    depends_on:
      - mongo

  rails:
    image: iambowen/railsitup
    ports:
      - "9292:9292"


###process_max_fds      