version: '2'
services:
  mongo:
    image: mongo
  event-service:
    image: iambowen/event-service
    environment:
      SPRING_PROFILES_ACTIVE: pact-test
      SERVER_PORT: 8080
    ports:
      - "8088:8080"
    depends_on:
      - mongo
  nagios:
    build: ./
    ports:
      - 10088:80
    links: 
      - 'event-service:event-service'      